Update Podfile
Example doesn't work, needs an update to platform. Otherwise, it says this error:

```
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
[!] CocoaPods could not find compatible versions for pod "React-RCTImage":
  In Podfile:
    React-RCTImage (from `../node_modules/react-native/Libraries/Image`)

Specs satisfying the `React-RCTImage (from `../node_modules/react-native/Libraries/Image`)` dependency were found, but they required a higher minimum deployment target.

Aborting run
An unexpected error was encountered. Please report it as a bug:
CocoaPodsError: Command `pod install` failed.
```